# Generated by Django 5.0.3 on 2024-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_account_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
