# Generated by Django 5.0.3 on 2024-07-22 10:16

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopping',
            name='userid',
            field=models.IntegerField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
