# Generated by Django 5.0.3 on 2024-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_alter_addshopping_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopping',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
