# Generated by Django 5.0.3 on 2024-07-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_alter_addshopping_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopping',
            name='Productid',
            field=models.CharField(max_length=1000),
        ),
    ]
