# Generated by Django 5.0.3 on 2024-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_alter_addshopping_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopping',
            name='Productid',
            field=models.IntegerField(max_length=1000),
        ),
    ]
