# Generated by Django 5.0.3 on 2024-07-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0012_alter_addshopping_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addshopping',
            old_name='Productid',
            new_name='Product_id',
        ),
    ]
