# Generated by Django 5.0.3 on 2024-07-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0013_rename_productid_addshopping_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addshopping',
            old_name='userid',
            new_name='user_id',
        ),
    ]
