# Generated by Django 5.0.3 on 2024-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0014_rename_userid_addshopping_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopping',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
