# Generated by Django 5.0.3 on 2024-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0015_alter_addshopping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopping',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
