# Generated by Django 5.0.3 on 2024-07-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0016_alter_addshopping_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addshopping',
            old_name='Product_id',
            new_name='Product',
        ),
    ]
