# Generated by Django 5.0.3 on 2024-08-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0019_alter_addshopping_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addshopping',
            old_name='Product_id',
            new_name='product_id',
        ),
    ]
