# Generated by Django 5.0.3 on 2024-08-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0021_alter_addshopping_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopping',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
